### ISSUE TITLE
Script fails with a 503 error. Seems service/region issue?

### ISSUE THREAD

**Issue by exelanz** [AnykeyNL/OCI-SuperDelete#18]
Hi, the script fails with a 503 error. Seems service/region issue. See output below. I don't think the data catalog service is available in that region and hence the script fails?

Region: me-dubai-1

--[ Deleting Data Catalogs ]--
Getting all Data Catalog objects
Traceback (most recent call last):
  File "delete.py", line 148, in <module>
    DeleteDataCatalog(config, processCompartments)
  File "/Users/arnoschots/oci-delete/OCI-SuperDelete/ocimodules/datacatalog.py", line 12, in DeleteDataCatalog
    items = oci.pagination.list_call_get_all_results(object.list_catalogs, compartment_id=Compartment.id).data
  File "/usr/local/lib/python3.8/site-packages/oci/pagination/pagination_utils.py", line 205, in list_call_get_all_results
    for response in list_call_get_all_results_generator(list_func_ref, 'response', *list_func_args, **list_func_kwargs):
  File "/usr/local/lib/python3.8/site-packages/oci/pagination/pagination_utils.py", line 274, in list_call_get_all_results_generator
    call_result = retry.DEFAULT_RETRY_STRATEGY.make_retrying_call(list_func_ref, *list_func_args, **list_func_kwargs)
  File "/usr/local/lib/python3.8/site-packages/oci/retry/retry.py", line 272, in make_retrying_call
    return func_ref(*func_args, **func_kwargs)
  File "/usr/local/lib/python3.8/site-packages/oci/data_catalog/data_catalog_client.py", line 5795, in list_catalogs
    return self.base_client.call_api(
  File "/usr/local/lib/python3.8/site-packages/oci/base_client.py", line 240, in call_api
    response = self.request(request)
  File "/usr/local/lib/python3.8/site-packages/oci/base_client.py", line 363, in request
    self.raise_service_error(request, response)
  File "/usr/local/lib/python3.8/site-packages/oci/base_client.py", line 528, in raise_service_error
    raise exceptions.ServiceError(
oci.exceptions.ServiceError: {'opc-request-id': '9DDD7D5DF22245F9A4AD990CDD19B452/E5EE4318A40109F27F1AF27068975CCE/7D72FE7BB125569A2E5BC5B5A1EAB10C', 'code': None, 'message': 'The service returned error code 503', 'status': 503}

**Comment by AnykeyNL** [comment]
Some service are not available in Dubai, so that is why it is erroring on queries these services. I believe this should not be fixed in the script.
